language: elixir

elixir:
  - 1.6.6

addons:
  postgresql: '11.0'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test