version: "3.6"

# Containers we are going to run
services:

  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build: .
    depends_on:
      # The db container needs to be started before we start this container
      - db
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: wedsite
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
      - "./priv/static:/app/priv/static"
      # - "/app/assets/elm/elm-stuff"


  db:
    # We use the predefined Postgres image
    image: postgres:11.0-alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

# Define the volumes
volumes:
  pgdata:
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
  

