FROM node:10.12-alpine

RUN npm install -g yarn

# RUN npm -g config set user root
# RUN npm -g install elm

WORKDIR /app/assets

COPY assets/package.json assets/*yarn* ./
RUN yarn install

COPY . .

CMD ["yarn", "run", "build"]