version: "3.6"

# Containers we are going to run
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: yarn run watch
    volumes:
      - ".:/app"
      - "static:/app/priv/static"

  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build: .
    depends_on:
      # The db container needs to be started before we start this container
      - db
      - webpack
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: wedsite
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
      - "static:/app/priv/static"

  db:
    # We use the predefined Postgres image
    image: postgres:11.0-alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define the volumes
volumes:
  pgdata:
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
  

